### ISSUE TITLE
Sujet en bullets points

### ISSUE THREAD

**Issue by melobern** [faboussard/42-irc#1]
## Partie obligatoire
**Nom du programme** : ircserv
**Fichiers de rendu** : Makefile, *.{h, hpp}, *.cpp, *.tpp, *.ipp, un fichier de configuration optionnel
**Makefile** : NAME, all, clean, fclean, re
- **Arguments** 
port : Le port d’écoute
password : Le mot de passe de connexion
- **Fonctions externes autorisées**
Tout ce qui respecte la norme C++ 98.

| Fonctions | ... | ... | ... |
|--------|--------|--------|--------|
| socket | close | setsockopt |  |
| getsockname | getprotobyname | gethostbyname |  |
| getaddrinfo |freeaddrinfo  |  |  |
| bind | connect | listen | accept | 
| htons | htonl | ntohs | ntohl | 
| inet_addr | inet_ntoa |  |  | 
| send | recv | signal | sigaction | 
| lseek | fstat | fcntl | poll (ou équivalent : select, kqueue, epoll) |

### Description Un serveur IRC en C++ 98
Vous devez développer un serveur IRC en C++ 98.
**Vous n’avez pas à développer un client. :warning: 
Vous ne devez pas gérer la communication de serveur à serveur.** :warning: 
Votre binaire devra être appelé comme ceci :
```shell
./ircserv <port> <password>
```
- [x]  **port** : Le numéro du port sur lequel votre serveur acceptera les connexions entrantes.
- [x] **password** : Le mot de passe permettant de s’identifier auprès de votre serveur
IRC, et qui devra être fourni par tout client IRC souhaitant s’y connecter.

Bien que poll() soit mentionné dans le sujet et la grille d’évaluation, vous pouvez utiliser un équivalent tel que select(), kqueue(), ou epoll().

### Prérequis
- [x] Le serveur doit pouvoir gérer plusieurs clients simultanément sans jamais bloquer.
• Le **forking est interdit**. Toute les opérations entrées/sorties doivent être non bloquantes. :warning: :red_circle: 
- [x] Vous n’avez le droit qu’à un seul poll() (ou équivalent) pour gérer toutes ces
opérations (read, write, mais aussi listen, etc.). :red_circle: 

Comme vous pouvez utiliser des FD en mode non bloquant, il est possible d’avoir un serveur non bloquant avec read/recv ou write/send tout en n’ayant pas recours à poll() (ou équivalent).
Mais cela **consommerait des ressources système inutilement.**
Ainsi, **si vous essayez d’utiliser read/recv ou write/send avec n’importe quel FD sans utiliser poll() (ou équivalent), votre note sera de 0**. :warning: :red_circle: :zero: 
- [x]  Il existe plusieurs clients IRC. Vous devez choisir l’un d’eux comme référence.
Votre client de référence sera utilisé pour l’évaluation.
- [x]  Votre client de référence doit pouvoir se connecter à votre serveur sans rencontrer d’erreur.
- [x]  La communication entre le client et le serveur se fera en TCP/IP (v4 ou v6).

Utiliser votre client de référence avec votre serveur devra être similaire à l’utiliser avec un serveur IRC officiel. Cependant, seules les fonctionnalités suivantes sont obligatoires :
- [x] Vous devez pouvoir vous authentifier, définir un nickname, un username, rejoindre un channel, envoyer et recevoir des messages privés, avec votre client de référence.
- [x]  Tous les messages envoyés par un client dans un channel doivent être transmis à tous les clients ayant rejoint ce channel.
- [x] Vous devez avoir des operators et des utilisateurs basiques.
- [x] #2
- **KICK** - Éjecter un client du channel
- **INVITE** - Inviter un client au channel
- **TOPIC** - Modifier ou afficher le thème du channel
- **MODE** - Changer le mode du channel :
— i : Définir/supprimer le canal sur invitation uniquement
— t : Définir/supprimer les restrictions de la commande TOPIC pour les opérateurs de canaux
— k : Définir/supprimer la clé du canal (mot de passe)
— o : Donner/retirer le privilège de l’opérateur de canal
— l : Définir/supprimer la limite d’utilisateurs pour le canal
- [x]  Bien entendu, on attend de vous un code propre.

## Exemple de test
- [x] Vérifiez absolument toutes les erreurs et tous les problèmes possibles (donnée partiellement reçue, bande passante faible, etc.).
Afin de vous assurer que votre serveur traite tout ce que vous lui envoyez, voici un test basique qui peut être fait avec nc :
```shell
\$> nc 127.0.0.1 6667
com^Dman^Dd
\$>
``` 

- [x] Utilisez ctrl+D pour envoyer la commande en plusieurs parties : ’com’, puis ’man’,
puis ’d\n’.
- [x] Afin de traiter une commande, vous devez en premier lieu la reconstituer en concaténant les paquets reçus.

## Partie bonus
Voici quelques fonctionnalités supplémentaires que vous pouvez ajouter à votre serveur afin qu’il soit encore plus proche d’un vrai serveur IRC :
• L’envoi de fichier.
• Un bot.

## Checks globaux
- [x] Vérifier les static (fonctions dans un seul fichier).
- [x] Effacer fonctions inutilisées.
- [x] Effacer commentaires vraiment useless et/ou les mettre en anglais.
- [x] Effectuer les tests de chaque commande 
       - [ ]  Mode
       - [ ] Join
       - [ ] Kick

**Comment by faboussard** [comment]
test for kick 

```
join #s
:admin JOIN :#s
:ircserv.localhost 331 admin #s :No topic is set
:ircserv.localhost 353 admin #s :@admin 
:ircserv.localhost 366 admin #s :End of \NAMES list


**kick #s**
:ircserv.localhost 461 admin KICK :Not enough parameters

**kick**
:ircserv.localhost 461 admin KICK :Not enough parameters

**kick #s adm**
:ircserv.localhost 401 admin adm :No such nick/channel

**kick #s nick**
:ircserv.localhost 441 admin nick #s :They aren't on that channel

:nick JOIN #s : say hello!
**kick #s nick :jojo**
:nick KICK #s :jojo
:nick PART #s : say goodbye!

:nick JOIN #s : say hello!
**kick #s nick jojo**
:nick KICK #s :jojo
:nick PART #s : say goodbye!


:nick JOIN #s : say hello!
**kick gg nick jojo**

```

**Comment by faboussard** [comment]
tests for join:

JOIN #s
:admin JOIN :#s
:ircserv.localhost 331 admin #s :No topic is set
:ircserv.localhost 353 admin #s :admin 
:ircserv.localhost 366 admin #s :End of NAMES list

JOIN + blank spaces → 461 Error: Not enough parameters.
JOIN # → 461 Error: Not enough parameters.
JOIN + 0 → PART from all channels
JOIN #channelA,#channelB → Successfully joins two channels.
JOIN ## → Joins one channel #
JOIN s -> :ircserv.localhost 476 admin s :Bad Channel mask

**Comment by faboussard** [comment]
tests for Mode:

Commandes censées fonctionner
```
MODE #channel +i -tk +o user1
MODE #channel +imst
MODE #channel +k password
MODE #channel +o user1 -o user1
MODE #channel +o user1 +o user2 +o user3 -o user4 +i -t
MODE #channel +o user1 +o user2 +o user3 -o user4
```
Commandes censées NE PAS fonctionner
```
MODE #channel +o user1 +o user2 +o user3 +o user4
MODE #channel +o
MODE #channel -o
MODE #channel +k
MODE #channel +l
```

**Comment by faboussard** [comment]
tests for privmsg

privmsg
:ircserv.localhost 461 nick PRIVMSG :Not enough parameters

 privmsg #s :haha
:nick PRIVMSG #s :haha

privmsg nick,admin :gg
:nick PRIVMSG nick :gg

privmsg @#s,@#h :g
:ircserv.localhost 401 nick #h :No such nick/channel

privmsg #s,admin :h
:ircserv.localhost 407 nick :Too many targets

privmsg #@s, "h
:ircserv.localhost 412 nick :No text to send

privmsg #@s :o
:ircserv.localhost 401 nick #@s :No such nick/channel

privmsg admin,    ,nick :p
:ircserv.localhost 412 nick :No text to send

privmsg #1,#2,#3,#4,#5 :g
:ircserv.localhost 407 admin :Too many targets

**Comment by ysengoku** [comment]
I had tried to make a very simple tester in bash to automate basic commands tests.
But it needs expected outputs for each tests.

If I have time after finishing bot, I'll retry a better tester.

[ysengoku / ft_irc-tester](https://github.com/ysengoku/ft_irc-tester)
