### ISSUE TITLE
Actual Crashes

### ISSUE THREAD

**Issue by melobern** [faboussard/42-irc#32]
:information_source: This issue must be closed at the very end of the project. Until then, we add every command that made the server crash.
We check them when we solve them and will happily retest them later :tada: 

- [x] `JOIN #42, #l l  ,#43` . To test it without the interactive mode : 
```sh
echo "PASS pass\r\nNICK nick\r\nUSER a a a :a\r\nJOIN #42, #l l  ,#43" | nc -C 127.0.0.1 6667
```

- [x] Do `PASS <valid pass>` 3 times before registration. To test it without the interactive mode : 
```sh
echo "PASS pass\r\nPASS pass\r\nPASS pass\r\nPASS pass\r\nPASS pass\r\nNICK nick\r\nUSER a a a :a\r\nJOIN #42, #l l  ,#43" | nc -C 127.0.0.1 6667
```
- [x] Do `QUIT` after having joined one or more channel. To test it without the interactive mode : 
```sh
echo "PASS pass\r\nNICK nick\r\nUSER a a a :a\r\nJOIN #42\r\nQUIT" | nc -C 127.0.0.1 6667
```

**Comment by faboussard** [comment]
crash apres un quit suivi dun join 0:

```
:nick PART #s : say goodbye!
quit
join 0
nc: write failed (0/2): Broken pipe
```

**Comment by ysengoku** [comment]
> netcat: crash apres un quit suivi dun join 0 (car on fait un part alors que plus rien nexiste...).
> 
> a tester sur hexchat 
> 
> 
> 
> ```
> 
> :nick PART #s : say goodbye!
> 
> quit
> 
> join 0
> 
> nc: write failed (0/2): Broken pipe
> 
> ```

Pour moi, ce n'est pas un Crash mais un comportement normal.
Au moment où un client a fait QUIT, il n'est plus connecté au server, donc fd est fermé (= write failed).
Le message vient du nc. 
Et je ne pense pas que le server puisse fermer le nc. C'est sur le terminal où le nc est lancé que l'on pourra arrêter le programme nc.
