### ISSUE TITLE
[HexChat] User A's Window Displays Only Members Joined After User A

### ISSUE THREAD

**Issue by ysengoku** [faboussard/42-irc#49]
User 1:
![hexchat1](https://github.com/user-attachments/assets/d6b0f56b-add9-4900-9133-6ffcf86210aa)

User 2 joined after User 1:
![hexchat2](https://github.com/user-attachments/assets/f325295b-308f-4f2e-985a-a7a0e0801301)

**Comment by faboussard** [comment]
fixed : the order was not correct in join (broadcast first)
