### ISSUE TITLE
fixing issues on mode and join (+ other minor fix + enhancement for part command) 

### ISSUE THREAD

**Issue by faboussard** [faboussard/42-irc#55]
**after celia s review ,  i fixed the following bugs :**

join:
- pas de caractères spéciaux : join #hey’ -> invalid , bad mask
- si je suis déjà dedans j'ai juste ce message qui pop, il faudrait que ça envoie rien dans le meilleur des cas
![image](https://github.com/user-attachments/assets/0619841f-453a-4216-b804-14c15d06c41d)
- quand j'ai join trop de channels et que je remet un channel dans lequel je suis déjà, je devrait pas avoir cette erreur
![image](https://github.com/user-attachments/assets/28752c66-6ec2-42bd-9a76-2848e8929f93)
-  les fonctions sendjoinmsg et sendPartmsg ont été enlevés, cela enlève des problemes de broken pipe et de spam de messages

Part:
- commande ajoutée
- un channel vide doit se suprimer automatiquement ==> **pouvez vous retester, j'ai l'impression que c'est ok** 

mode:
- si on entre juste + ou - , ça retourne
- le uint8 de limit faisait que la limite int 65 se transformait en A
- si on etnre 0 en limite, ça désactive la limite. 
- overflow contrôlé 
- j'ai retiré les sendNotice qui polluaient

parsing :  
- les messages de plus de 512 char sont trunked
- les empty messages ignored (le /r a été trim en plus du / n) 

je n'ai pas regardé les autres erreurs sur lauthentification + les histoire de  ":"qu a relevé Célia, puisque le fonctionnement me parait bien, et nous on gère aussi cela pour que ça marche bien sur nc et hexchat.

nb : pour privmsg, si le sender envoie dans un seul canal, il ne recevra pas. je n'ai pas trouvé d'autre moyen car hexchat ajoute le #canal en lousdé meme quand on ne le tape pas, et donc je n'ai pas trouvé d'aures solutions (sinon il faudrait changer les paramètres de hexchat mais la version de l'école semble ne pas le permettre de toutes façons ... ) 

Si c'est bon pour toi Yuko, je mergerai demain sur main

**Comment by ysengoku** [comment]
@faboussard Peux-tu faire PR ? Ce sera plus simple pour checker.

**Comment by faboussard** [comment]
> @faboussard Peux-tu faire un PR ? Ce sera plus simple pour checker.

Oui je fais ça !

**Comment by ysengoku** [comment]
Regarding channel names, I saw this in the RFC1459 protocol.
If I understood correctly, only `' ' (spaces`), `control G`, and `',' (comma)`, channel prefixes `&` and  `#` are prohibited in names?
I saw the same thing in RFC2811.

> Channel names are strings (beginning with a & or # character) of length up to 200 characters. Apart from the requirement that the first character is either & or #, the only restriction on a channel name is that it may not contain any spaces (' '), a control G (^G or ASCII 7), or a comma (, which is used as a list item separator by the protocol).
